version: "3.3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8585:8080
    volumes:
      - /home/bailey:/data
      - /home/bailey/Docker/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
