---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/bailey/Docker/Radarr/config:/config
      - /home/bailey/Server/Movies:/movies #optional
      - /home/bailey/Docker/Torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/bailey/Docker/Sonarr/config:/config
      - /home/bailey/Server/TV:/tv #optional
      - /home/bailey/Docker/Torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional
    volumes:
      - /home/bailey/Docker/Jackett/config:/config
      - /home/bailey/Docker/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/bailey/Docker/Bazarr/config:/config
      - /home/bailey/Server/Movies:/movies #optional
      - /home/bailey/Server/TV:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
