version: '3.3'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: kopia-host
        container_name: kopia
        restart: unless-stopped
        ports:
            - 51516:51516
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51516
            - --server-username=${SERVER_USERNAME}
            - --server-password=${SERVER_PASSWORD}
        environment:
            USER: ${USER}
            KOPIA_PASSWORD: ${KOPIA_PASSWORD}
            KOPIA_PERSIST_CREDENTIALS_ON_CONNECT: true
        volumes:
            # Mount local folders needed by kopia (edit these to whatever you want)
            # LOCAL
            - /home/bailey:/serverHomeDir
            - /mnt/backup/Kopia:/externalBackupFolder
            # REMOTE
            - /home/bailey/Docker/NextCloud/data/data:/nextcloudData
            # General
            - /home/bailey/Docker/KopiaLocal/app/config:/app/config
            - /home/bailey/Docker/KopiaLocal/app/cache:/app/cache
            - /home/bailey/Docker/KopiaLocal/app/logs:/app/logs
            - /home/bailey/Docker/KopiaLocal/repository:/repository
            - /home/bailey/Docker/KopiaLocal/KopiaTemp:/tmp:shared

