version: '3.3'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: kopia-host
        container_name: kopia
        restart: unless-stopped
        ports:
            - 51516:51516
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51516
            - --server-username=${SERVER_USERNAME}
            - --server-password=${SERVER_PASSWORD}
        volumes:
            # Mount local folders needed by kopia (edit these to whatever you want)
            - /home/bailey/Docker/KopiaRemote/app/config:/app/config
            - /home/bailey/Docker/KopiaRemote/app/cache:/app/cache
            - /home/bailey/Docker/KopiaRemote/app/logs:/app/logs
            # Mount repository location
            - /home/bailey/Docker/KopiaRemote/repository:/repository
            # Mount path for browsing mounted snaphots
            - /home/bailey/Docker/KopiaTemp:/tmp:shared
