version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8098:8081"
    volumes:
      - /home/bailey/Server/SharedFolder/YTDownloads:/downloads
